package com.codewars.level7;

/*A coloured triangle is created from a row of colours,
each of which is red, green or blue.
Successive rows, each containing one fewer colour than the last,
are generated by considering the two touching colours in the previous row.
If these colours are identical,
the same colour is used in the new row.
If they are different, the missing colour is used in the new row.
This is continued until the final row, with only a single colour, is generated.
*/
public class ColouredTriangles {
    public static char triangle(final String row) {
        char[] basic = row.toCharArray();
        char rez = rec(basic)[0];
        return rez;
    }

    public static char[] rec(char arr[]) {
        if (arr.length == 1)
            return arr;
        char[] temp = new char[arr.length - 1];
        for (int i = 0; i < arr.length - 1; i++) {
            if (arr[i] == arr[i + 1]) {
                temp[i] = arr[i];
            } else if ((arr[i] == 'B' && arr[i + 1] == 'G') || (arr[i] == 'G' && arr[i + 1] == 'B')) {
                temp[i] = 'R';
            } else if ((arr[i] == 'R' && arr[i + 1] == 'G') || (arr[i] == 'G' && arr[i + 1] == 'R')) {
                temp[i] = 'B';
            } else if ((arr[i] == 'B' && arr[i + 1] == 'R') || (arr[i] == 'R' && arr[i + 1] == 'B')) {
                temp[i] = 'G';
            }
        }
        return rec(temp);
    }
}
